name: ccis01
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4122
title: CCIS-01
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00aff0'
    - '#ffffff'
    - '#3e4095'
    - '#c4c4dd'
    - '#807f80'
  brandStrength: 0.25
  lightness: 0.8487170517910272
  saturation: 0.2972318350803107
  rhythmicContrast: 0.21741429646499455
purpose: []
