name: ccis01
favicon: null
layout_spectrum: 0.32696267566643655
typography_spectrum: 0.12131639989092946
title: CCIS-01
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.26189738675020635
  lightness: 0.8487170517910272
  saturation: 0.2972318350803107
  rhythmicContrast: 0.21741429646499455
purpose: []
