analytics: {}
color:
  brandColors:
    - '#00aff0'
    - '#ffffff'
    - '#3e4095'
    - '#c4c4dd'
    - '#807f80'
  brandStrength: 0.25
  lightness: 0.8487170517910272
  rhythmicContrast: 0.21741429646499455
  saturation: 0.2972318350803107
cta: {}
layout_spectrum: 0.21176
name: ccis01
opengraph: {}
purpose: []
typography_spectrum: 0.638158
